### ISSUE TITLE
pushover LICENSE

### ISSUE THREAD

**Issue by fommil** [emilypi/entropy#1]
![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fi.warosu.org%2Fdata%2Fg%2Fimg%2F0553%2F33%2F1467269171088.jpg&f=1)

**Comment by emilypi** [comment]
LOL. 

```
Join us now and share the software;
You'll be free, hackers, use BSD.
Join us now and share the software;
You'll be free, hackers, you'll be free.
```

From the man the myth the legend himself
